# Generated by Django 4.2 on 2023-05-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productImage', models.ImageField(upload_to='')),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
    ]
